// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_SXBldTPlBrLhxxQfLbvG8DVsIv_8jyw',
    appId: '1:1080176402729:web:fecf3490b752155c15d738',
    messagingSenderId: '1080176402729',
    projectId: 'streamchecker-50d69',
    authDomain: 'streamchecker-50d69.firebaseapp.com',
    storageBucket: 'streamchecker-50d69.firebasestorage.app',
    measurementId: 'G-FVYQJNF0ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClQFefZD4ZOBfHD5pH5CO-LaJOBoC9zUU',
    appId: '1:1080176402729:android:4a391a562a4f681815d738',
    messagingSenderId: '1080176402729',
    projectId: 'streamchecker-50d69',
    storageBucket: 'streamchecker-50d69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgDbg43uq2vkb875-QbAzVpxvA_yuy1dM',
    appId: '1:1080176402729:ios:dc96e1f936a740f615d738',
    messagingSenderId: '1080176402729',
    projectId: 'streamchecker-50d69',
    storageBucket: 'streamchecker-50d69.firebasestorage.app',
    iosBundleId: 'com.example.streamCheck',
  );
}
